### ISSUE TITLE
[FEATURE] Support for saving/loading to external files

### ISSUE THREAD

**Issue by Jefferderp** [benjamonnguyen/obsidian-inline-todotxt#18] opened 2024-01-21 00:53 UTC
Hello! I love this plugin, but one downside to the codeblocks approach is that your tasks live in a .md file which isn't portable to any other todo.txt management apps.

If it were possible to load to and from a neighboring todo.txt file, this would make the plugin immensely useful to me.

Thanks very much!

**Comment by benjamonnguyen** [comment] 2024-01-21 20:21
I think this is an essential feature too! Here's the implementation I'm thinking of...

There will be a "link" button that allows you to populate the codeblock from the todotxt file at the provided path.

This will add the `src` metadata to the header like so: 

'''todotxt "Title" src:path/to/todo.txt

Once linked, the button will be replaced with a "save" button that will persist whatever is in the codeblock to the file whenever clicked.

I'll add a confirmation popup that can be disabled in the settings. 

Thoughts?

**Comment by Jefferderp** [comment] 2024-01-21 20:30
Definitely! That sounds like a great implementation.

My only other suggestion is to include an option for automatic saving, after the user has finished interacting (on an automatic delay).

My `todo.txt` file exists in my Obsidian vault, but my vault is backed by an external syncing program (Syncthing). If I had to click Save manually, I'd eventually forget. And then the changes would not be propagated to disk, causing problems when I went to edit my `todo.txt` on a different device (such as my phone).

**Comment by Jefferderp** [comment] 2024-01-21 20:30
To add to that - it would also be important that any external changes to the `todo.txt` file were detected and imported.

**Comment by benjamonnguyen** [comment] 2024-01-22 00:49
The reason I want saving to be manual is so whether the codeblock overwrites the file and vice versa can be controlled without a complicated synchronization mechanism.

**Comment by Jefferderp** [comment] 2024-01-22 00:54
Ok, I totally understand. This would still be a useful feature, and thanks!

**Comment by benjamonnguyen** [comment] 2024-01-28 21:09
Hey @Jefferderp, I've implemented the feature as part of [Release 0.2.0](https://github.com/benjamonnguyen/obsidian-todotxt-codeblocks/releases/tag/0.2.0)

I'll be testing it myself over the next week or 2 before releasing it and would really appreciate it if you could help me beta test too using the BRAT plugin (https://tfthacker.com/brat-quick-guide).

FYI, I managed to implement it with automatic saves and syncs as you suggested!

**Comment by Jefferderp** [comment] 2024-01-28 21:36
Awesome, thanks very much! I'll give this a test very soon.

**Comment by udjer** [comment] 2024-01-29 12:23
The plugin looks really cool, thank you!  Just installed and tested v.0.2.0...

Re automatic syncs (tested in obsidian 1.5.3 on MacOS 10.15.7):
- the codeblock is saved (though timing/trigger event isn't clear to me),
- the codeblock isn't read if the file has been changed externally (so, external changes are overwritten).

Honestly, I'd prefer to manually read/write the file (in order to have full control).

**Comment by benjamonnguyen** [comment] 2024-01-29 15:19
@udjer let me add a fix for what you're seeing and add a setting to toggle auto-sync

**Comment by udjer** [comment] 2024-01-29 19:43
Hi @benjamonnguyen,

> @udjer let me add a fix for what you're seeing and add a setting to toggle auto-sync

thanks a lot for the swift response - no rush with fix or added setting, testing takes time (let me know if you need more info)...

Another option to address @Jefferderp's concern might be to check whether codeblock and file differ upon opening/closing the file containing the todo.txt codeblock and throwing a warning/dialog if they are different?
But perhaps that's more cumbersome or error prone than an auto-sync toggle setting.

**Comment by benjamonnguyen** [comment] 2024-01-31 05:33
@udjer Hey! Overwrite issue should be resolved in v0.2.1, but let me know if the lack of clarity persists as you continue to use it.

@Jefferderp The plugin should be able to coexist with openasmd now

**Comment by udjer** [comment] 2024-02-01 08:33
@benjamonnguyen Fab, thanks a lot - now, external changes are loaded and internal changes are reflected in the file.  So, everything works as intended.  Thanks for the swift resolution!

**Closed as completed** 2024-02-07 15:46 UTC

**Comment by udjer** [comment] 2024-09-02 15:38
Hi benjamonnguyen,

I just noticed a possibly unexpected/unwanted behaviour syncing the codeblock with an associated todo.txt file: making a change to the codeblock
- in "normal" editing mode, the change is written to the file;
- in source editing mode, the change is overwritten by the next file sync.

I don't think it matters much (at least not to me) but is a bit unexpected.

An option to disable automatic sync and manually read from/write to the todo.txt file may be useful?

**Comment by benjamonnguyen** [comment] 2024-09-02 16:41
Source mode essentially disables the plugin. Manual syncing wouldn't be feasible since the underlying logic relies on the idea of atomic actions (like when I add, edit, or delete a task).

**Comment by udjer** [comment] 2024-09-02 19:56
Ah, I see - thanks for the explanation.
